### ISSUE TITLE
Could not find or load main class com.nobility.downloader.Main

### ISSUE THREAD

**Issue by FireQuacker** [NobilityDeviant/Wcofun.com_Downloader#11]
Ran .jar file within the .zip and got this error

java -jar TWCD.jar
Error: Could not find or load main class com.nobility.downloader.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

**Comment by NobilityDeviant** [comment]
Did you read the read me?
[https://github.com/NobilityDeviant/Wcofun.com_Downloader#requirements](Read Me)
you are most likely using a version without javafx

**Comment by FireQuacker** [comment]
I thought it was optional if we had java from oracle, but I downloaded it and it worked! Thank you!
