### ISSUE TITLE
[bug]: Videos still don't download in higher resolution

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [NobilityDeviant/Wcofun.com_Downloader#14]
I just downloaded the latest released 2.0. I tried to download bluey in 1080p, but the videos were still in 480p (or 576p in the program). I mean, the episode I was downloading had 720p and 480p (HD and SD).

OS: Windows 10
Browser (selected in WcoDownloader): Firefox
WcoDownloader version: 2.0
Episode link: https://www.wcofun.org/bluey-season-3-episode-24-faceytalk

**Comment by NobilityDeviant** [comment]
I have not tested all browsers and all series and some of them are a little weird
i will look into this later tonight and the chrome issue

**Comment by NobilityDeviant** [comment]
Issue fixed with [2.0.1](https://github.com/NobilityDeviant/Wcofun.com_Downloader/releases/tag/2.0.1)

Closing this one. Please comment on [This issue](https://github.com/NobilityDeviant/Wcofun.com_Downloader/issues/13) if there are anymore problems.
