### ISSUE TITLE
Download Folder setting fails to save/errors out if not put on a secondary drive

### ISSUE THREAD

**Issue by iSharingan** [NobilityDeviant/Wcofun.com_Downloader#2]
Attempting to set the download folder to one on the same drive as the program results in the following (Windows 10):

![Error](https://user-images.githubusercontent.com/3332462/202931488-c0c7b5c4-641f-4243-b8fc-f0a4f203f592.PNG)

Setting it to an external drive behaves as expected.

**Comment by NobilityDeviant** [comment]
Weird. I have not had this issue before even with a 10GB drive. You have enough space in your drive correct?
I will test this is out alongside the other issue. Thanks!

**Comment by iSharingan** [comment]
I'm using a dual boot setup (had a game that needed a different OS to launch than my preferred one) and this is the larger hard drive. The drive itself is 4TB with over 75% free space, which might be the cause of the error if the drive size/available space is overflowing the variable size you set for the check.

**Comment by NobilityDeviant** [comment]
The way the program checks for free space relies on a lot of security checks. I have added ways to check it a little better and skip this space check all together. I will release it later today.

**Comment by iSharingan** [comment]
Come to think of it, another possible cause is unexpected characters (most likely a space in my case) in the file path, causing the function to return null for the available space at the destination. This would mean the same issue could crop up in other file path calls that aren't properly stored/formatted, such as preventing files form being saved/loaded.

**Comment by iSharingan** [comment]
The exact setup is Windows 7 on my main 1 terabyte drive, and windows 10 on a second 4 terabyte drive. Booting to Win 10 makes the second drive become C (dual boot on the same drive isn't likely to be possible unless the first OS is Linux do to how windows bootstrapping works iirc). I'll probably do some digging on similar issues in other programs since rare as this is, this can't be the first time someone had to fix it.

As for debugging, an output of the exact space found at the target as well as the variable for the target folder path would likely give the best idea of whats going on (would indicate any problems with the file path string and if Null/an overflow value is being returned for this any any future issues)

In any case, simply dragging completed files to the other drive is working reasonably well so far. This doesn't need to be a high priority fix by any means.

**Comment by AppleCanon** [comment]
I like how it works for 2 series then fails for any link put in after XD.

**Comment by iSharingan** [comment]
if it fails when scraping the series for links/data (just after it downloads the series' image. returns an error outside the expected range of 0 or something) I just tell it immediately to start again and everything loads fine. I just did like 12 series in a row that way.

**Comment by NobilityDeviant** [comment]
> The exact setup is Windows 7 on my main 1 terabyte drive, and windows 10 on a second 4 terabyte drive. Booting to Win 10 makes the second drive become C (dual boot on the same drive isn't likely to be possible unless the first OS is Linux do to how windows bootstrapping works iirc). I'll probably do some digging on similar issues in other programs since rare as this is, this can't be the first time someone had to fix it.
> 
> As for debugging, an output of the exact space found at the target as well as the variable for the target folder path would likely give the best idea of whats going on (would indicate any problems with the file path string and if Null/an overflow value is being returned for this any any future issues)
> 
> In any case, simply dragging completed files to the other drive is working reasonably well so far. This doesn't need to be a high priority fix by any means.

I am still convinced this is a permissions issue. Have you tried running the program as admin? There would be no overflow or null values because it always checks them beforehand. It even checks for write permissions so i am not sure whats going on, but java is weird especially on linux

It specifically uses 

`      val downloadFolder = File(store.stringSetting(Defaults.SAVEFOLDER))
        if (!downloadFolder.exists()) {
            showError("The downloader folder in your settings doesn't exist. You must set it up before downloading videos.")
            openSettings(0)
            return false
        }
        try {
            if (!downloadFolder.canWrite()) {
                showError(
                    "The download folder in your settings doesn't allow write permissions." +
                            "\nIf this is a USB or SD Card then disable write protection." +
                            "\nTry selecting a folder in the user or home folder. Those are usually not restricted."
                )
                openSettings(0)
                return false
            }
        } catch (e: Exception) {
            showError("Failed to check for write permissions.", e)
            return false
        }`

Which handles everything when pressing start. I think it has something to do with the series folders if anything, but even then it will just default to the main folder.
I have noticed series folders not working even if they are created so ill look into that.




> I like how it works for 2 series then fails for any link put in after XD.

You have to be more specific then that. It could just be wcofun or your internet being slow.



> if it fails when scraping the series for links/data (just after it downloads the series' image. returns an error outside the expected range of 0 or something) I just tell it immediately to start again and everything loads fine. If the series's link has been entered previously/the series logo/image has been downloaded, the error doesn't occur. I just did like 12 series in a row that way.

I believe i know what's wrong here. But you should try placing the program folder in the drive that's not causing problems or try running it as admin. It just seems to be all related to the drive.
I am adding some failsafe checks but that doesn't entirely solve your issue.

**Comment by NobilityDeviant** [comment]
If this keeps happening then open another issue.
