### ISSUE TITLE
Error: Could not find or load main class TWCD.jar

### ISSUE THREAD

**Issue by yash-10x** [NobilityDeviant/Wcofun.com_Downloader#4]
Error: Could not find or load main class TWCD.jar
![Screenshot (1)](https://user-images.githubusercontent.com/98729131/206157911-7c403644-5f7d-454b-a8a2-0402b8f8dbdc.png)

**Comment by NobilityDeviant** [comment]
The command is java -jar TWCD.jar

**Comment by yash-10x** [comment]
> The command is java -jar TWCD.jar

Error: Could not find or load main class com.nobility.downloader.Main

**Comment by NobilityDeviant** [comment]
I believe it's due to openjdk because it doesn't come with javafx,
Since it looks like you are running it inside some sort of linux sandbox, you can try 
sudo apt-get install openjfx
Not sure if it's compatible though
If you can't figure it out you can use liberica instead https://bell-sw.com/pages/downloads/#/java-8-lts

**Comment by NobilityDeviant** [comment]
one day i will ditch javafx in favor of jetpack compose, but that could take awhile

**Comment by yash-10x** [comment]
thank you for help i am sorry for late reply

**Comment by CesiumCs** [comment]
Had this issue too. Maybe you could note this in the readme? I know it already states which specific Java is used but it would help people like me who figured they were functionally interchangeable and didn't realize it wouldn't work on openjdk

**Comment by NobilityDeviant** [comment]
> Had this issue too. Maybe you could note this in the readme? I know it already states which specific Java is used but it would help people like me who figured they were functionally interchangeable and didn't realize it wouldn't work on openjdk

Yes that's a good idea

**Comment by NobilityDeviant** [comment]
I have updated the readme.
