### ISSUE TITLE
Error: Could not find or load main class com.nobility.downloader.Main

### ISSUE THREAD

**Issue by FireQuacker** [NobilityDeviant/Wcofun.com_Downloader#5]
After following install instructions I get this error

Error: Could not find or load main class com.nobility.downloader.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

I have reinstalled java a few times, Ive downloaded the current and all previous versions of TWCD.jar

**Comment by NobilityDeviant** [comment]
And you have follow https://github.com/NobilityDeviant/Wcofun.com_Downloader#requirements ?
You cant use openjdk by itself if that's what you're trying to do.

You can also refer to this issue https://github.com/NobilityDeviant/Wcofun.com_Downloader/issues/4

**Comment by NobilityDeviant** [comment]
If this keeps happening then open another issue.
