### ISSUE TITLE
Possible to download HD versions?

### ISSUE THREAD

**Issue by ghamson** [NobilityDeviant/Wcofun.com_Downloader#6]
This is a great tool and I've managed to get it working... however the quality it downloads is very low compared to the version that streams in my browser.

Is there something I can do to force the higher quality versions to come down?

Thanks again for the tool

**Comment by NobilityDeviant** [comment]
Thank you for your kind words
I believe it is possible. I will look into it as i push a couple of new updates

**Comment by Joshezpz** [comment]
This has saved me so much time, thank you for your efforts. Is there an update on the HD / Blu-Ray compat?

**Comment by ego-lay-atman-bay** [comment]
Any updates?

**Comment by NobilityDeviant** [comment]
I am creating a new update and I will look deeper into this.
Might take awhile

**Comment by NobilityDeviant** [comment]
Made a break through. Found a wacky hacky way to change the resolution.
Fully implemented inside the W.I.P
The download is really slow though, but it's still an option.
New version will be released soon.

**Comment by Joshezpz** [comment]
Good lad, thanks again. Can't wait.

**Comment by NobilityDeviant** [comment]
Feature has been added with version [2.0](https://github.com/NobilityDeviant/Wcofun.com_Downloader/releases/tag/2.0)
