### ISSUE TITLE
![Error 4_30_2023 8_51_45 PM](https://user-images.githubusercontent.com/40222220/235389785-e1a4bcb2-cc9a-4f50-a158-e56332d7fdd0.png)

### ISSUE THREAD

**Issue by Mr-Halpin001** [NobilityDeviant/Wcofun.com_Downloader#9]
![Error 4_30_2023 8_51_45 PM](https://user-images.githubusercontent.com/40222220/235389785-e1a4bcb2-cc9a-4f50-a158-e56332d7fdd0.png)

_Originally posted by @KreeperSteve in https://github.com/NobilityDeviant/Wcofun.com_Downloader/issues/8#issuecomment-1529242498_

**Comment by Mr-Halpin001** [comment]
I have updated and upgraded the Selenium, chrome driver, chrome, and python but the error still persists.

**Comment by NobilityDeviant** [comment]
Sorry everybody i have been on a long break. I have identified the error and have fixed it.
Will be releasing a new update soon.
